GET http://localhost:3000/events

###
GET http://localhost:3000/events/{{ eventId }}

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "São João",
    "description": "Caruaru the capytal of Forro",
    "date": "2025-06-18T00:00:00",
    "price": 250
}

###
@eventId = {{ createEvent.response.body.id }}

###
PATCH http://localhost:3000/events/{{ eventId }}
Content-Type: application/json

{
    "name": "São João",
    "description": "Caruaru, the capital of Forro",
    "date": "2024-06-18T00:00:00",
    "price": 100
}

###
DELETE http://localhost:3000/events/{{ eventId }}

###
GET http://localhost:3000/events/{{ eventId }}/spots

###
# @name createSpot
POST http://localhost:3000/events/{{ eventId }}/spots
Content-Type: application/json

{
    "name": "IA"
}

###
@spotName = {{ createSpot.response.body.name }}

###
# @name createReserve
POST http://localhost:3000/events/{{ eventId }}/reserve
Content-Type: application/json

{
    "spots": ["{{spotName}}"],
    "ticket_kind": "full",
    "email": "rogiborgessouza@outlook.com"
}